on:
  discussion_comment:
    types: [created]

name: "Vouch - Manage by Discussion"

concurrency:
  group: vouch-manage
  cancel-in-progress: false

jobs:
  manage:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.VOUCH_APP_ID }}
          private-key: ${{ secrets.VOUCH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: mitchellh/vouch/action/manage-by-discussion@c6d80ead49839655b61b422700b7a3bc9d0804a9 # v1.4.2
        with:
          discussion-number: ${{ github.event.discussion.number }}
          comment-node-id: ${{ github.event.comment.node_id }}
          vouch-keyword: "!vouch"
          denounce-keyword: "!denounce"
          unvouch-keyword: "!unvouch"
          pull-request: "true"
          merge-immediately: "true"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
